name: deploy a bot

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkin
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ls_check
        run: ls -la

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build an image
        run: docker build -t numbers_bot:latest . --build-arg ${{ secrets.TOKEN }}
