name: deploy a bot

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: checkin
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ls
        run: ls -la

      - name: clearing old container
        run: |
          cd docker
          docker-compose stop

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build an image
        run: docker build -t numbers-bot:latest . --build-arg BOT_TOKEN=${{ secrets.TOKEN }}

      - name: push docker image
        run: |
          docker tag numbers-bot:latest ${{secrets.DOCKER_USERNAME}}/numbers-bot
          docker push ${{secrets.DOCKER_USERNAME}}/numbers-bot:latest

      - name: run a bot
        run: |
          docker run -d numbers-bot